package:
  name: libstatiskit_linalg
  version: {{ GIT_DESCRIBE_VERSION }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  
about:
  home: http://statiskit-linalg.readthedocs.org
  license: Apache License 2.0
  summary: C++ Library for Minimal Interpreted Interfaces of the Eigen C++ Template Library
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtoolchain
  host:
    - libstatiskit_stl-dev