##################################################################################
#                                                                                #
# PyClangLite: Python bindings for Clang                                         #
#                                                                                #
# Homepage: http://pyclanglite.readthedocs.io/                                   #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (3)                        #
#                                                                                #
##################################################################################

package:
  name: python-statiskit_linalg
  version: "3.3.1"

source:
  path: ../..

build:
  number: 0
        
about:
  home: statiskit.readthedocs.org
  license: CeCILL-C

requirements:
  build:
    - libdev
    - python-dev
    - libboost
    - eigen 3.3.1
    - libstatiskit_linalg
    - python
  run:
    - librun
    - libstatiskit_linalg
    - libboost
    - python

test:                                                           
  source_files:                                
    - test
  requires:
    - python-dbg
  commands:                                       
   - nosetests test -x -s -v --with-coverage --cover-tests --cover-package=statiskit.linalg
