package:
  name: python-statiskit_linalg
  version: {{ GIT_DESCRIBE_VERSION }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
        
about:
  home: http://statiskit-linalg.readthedocs.org
  license: Apache License 2.0
  summary: Python Minimal Interpreted Interface of the Eigen C++ Template Library

requirements:
  build:
    - python-toolchain
    - libtoolchain
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libboost-dev
    - libboost_python
    - libstatiskit_linalg-dev
    - libstatiskit_linalg
    - python
  run:
    - {{ pin_compatible('libboost_python', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('libstatiskit_linalg', exact=True) }}
    - python

test:                                               
  requires:
    - python-toolchain
    - matplotlib
  imports:
    - statiskit.linalg
  source_files:                                
    - test/test_*.py
  commands:                                       
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and linux" [linux]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and osx"   [osx]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and win"   [win]
