package:
  name: libstatiskit_linalg
  version: "3.3.1"

source:
  path: ../../..

build:
  number: 0
  
about:
  home: http://statiskit-linalg.readthedocs.org
  license: Apache License 2.0
  summary: Minimal Interpreted Interfaces for the Eigen C++ Template Library
  
requirements:
  build:
    - libeigen
    - libtoolchain
    - libstatiskit_stl
  run:
    - libeigen
    - libstatiskit_stl
