package:
  name: libstatiskit_linalg
  version: "3.3.1"

source:
  path: ../../..

build:
  number: 0
  
about:
  home: http://statiskit-linalg.readthedocs.org
  license: Apache License 2.0
  summary: C++ Library for Minimal Interpreted Interfaces of the Eigen C++ Template Library
  
requirements:
  build:
    - libtoolchain
    - libstatiskit_stl-dev
    - libstatiskit_linalg-dev
  run:
    - libstatiskit_stl
