package:
  name: libstatiskit_linalg
  version: "3.3.1"

source:
  path: ../..

build:
  number: 0
  
about:
  home: http://statiskit-linalg.readthedocs.org
  license: CeCILL

requirements:
  build:
    - eigen
    - libdev
  run:
    - eigen
    - librun