package:
  name: libstatiskit_linalg
  version: "3.3.1"

source:
  path: ../..

build:
  number: 0
  
about:
  home: statiskit.readthedocs.org
  license: CeCILL

requirements:
  build:
    - eigen 3.3.1
    - libdev
  run:
    - eigen 3.3.1
    - librun