package:
  name: libeigen-dev
  version: "3.3.1"

source:
  fn: eigen-3.3.1.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/3.3.1.tar.gz
  sha256: 3c9d2c1f86eee404de99f4238b24c3a737e6ec963a325d443878fa59f6eb2a90
  
build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  
about:
  home: http://statiskit-linalg.readthedocs.org
  license: Apache License 2.0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtoolchain
    - libtoolchain-dev