package:
  name: autowig-libstatiskit_linalg
  version: {{ GIT_DESCRIBE_VERSION }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  detect_binary_files_with_prefix: False

about:
  home: http://statiskit-stl.readthedocs.org
  license: Apache License 2.0
  summary: Minimal Interpreted Interfaces for Containers of the STL C++ Template Library

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtoolchain
    - libtoolchain-dev
    - autowig-toolchain
    - autowig-libstatiskit_stl
  host:
    - autowig-libstatiskit_stl
    - libstatiskit_linalg-dev
    - python
  run:
    - {{ pin_compatible('libstatiskit_linalg-dev', exact=True) }}
    - {{ pin_compatible('autowig-libstatiskit_stl', exact=True) }}
    - python