package:
  name: libstatiskit_linalg-dev
  version:  {{ GIT_DESCRIBE_VERSION }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  detect_binary_files_with_prefix: False

about:
  home: http://statiskit-stl.readthedocs.org
  license: Apache License 2.0
  summary: C++ Development Files for Minimal Interpreted Interfaces of the Eigen C++ Template Library

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtoolchain
    - libtoolchain-dev
    - autowig-toolchain
  host:
    - libstatiskit_stl-dev
    - libeigen-dev
    - python
  run:
    - {{ pin_compatible('libeigen-dev', exact=True) }}