package:
  name: libeigen-dev
  version: "3.3.1"

source:
  fn: eigen-3.3.1.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/3.3.1.tar.gz

build:
  number: 0
  
about:
  home: http://statiskit-linalg.readthedocs.org
  license: Apache License 2.0

requirements:
  build:
    - libtoolchain
  run:
    - libruntime
